/// Flutter icons TeslorIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TeslorIcons
///      fonts:
///       - asset: fonts/TeslorIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TeslorIcons {
  TeslorIcons._();

  static const _kFontFam = 'TeslorIcons';
  static const String? _kFontPkg = null;

  static const IconData frunk = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fan = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
